<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKV8O08I\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKV8O08I/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKV8O08I.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKV8O08I\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKV8O08I\App_KernelDevDebugContainer([
    'container.build_hash' => 'KV8O08I',
    'container.build_id' => '5e42754d',
    'container.build_time' => 1724764291,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKV8O08I');
