<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_xdebug' => [[], ['_controller' => 'web_profiler.controller.profiler::xdebugAction'], [], [['text', '/_profiler/xdebug']], [], [], []],
    '_profiler_font' => [['fontName'], ['_controller' => 'web_profiler.controller.profiler::fontAction'], [], [['text', '.woff2'], ['variable', '/', '[^/\\.]++', 'fontName', true], ['text', '/_profiler/font']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    'app_client_calendar' => [[], ['_controller' => 'App\\Controller\\CalendarController::calendar'], [], [['text', '/calendar']], [], [], []],
    'app_client_accueil' => [[], ['_controller' => 'App\\Controller\\DashboardController::accueil'], [], [['text', '/dashboard']], [], [], []],
    'app_client_login' => [[], ['_controller' => 'App\\Controller\\DefaultController::accueil'], [], [['text', '/']], [], [], []],
    'app_client_products_stock_list' => [[], ['_controller' => 'App\\Controller\\ProduitsController::stock'], [], [['text', '/stock']], [], [], []],
    'app_client_products_stock_add_produit' => [[], ['_controller' => 'App\\Controller\\ProduitsController::addProducts'], [], [['text', '/addProduit']], [], [], []],
    'app_client_products_reassort' => [[], ['_controller' => 'App\\Controller\\ProduitsController::reassort'], [], [['text', '/reassort']], [], [], []],
    'App\Controller\CalendarController::calendar' => [[], ['_controller' => 'App\\Controller\\CalendarController::calendar'], [], [['text', '/calendar']], [], [], []],
    'App\Controller\DashboardController::accueil' => [[], ['_controller' => 'App\\Controller\\DashboardController::accueil'], [], [['text', '/dashboard']], [], [], []],
    'App\Controller\DefaultController::accueil' => [[], ['_controller' => 'App\\Controller\\DefaultController::accueil'], [], [['text', '/']], [], [], []],
    'App\Controller\ProduitsController::stock' => [[], ['_controller' => 'App\\Controller\\ProduitsController::stock'], [], [['text', '/stock']], [], [], []],
    'App\Controller\ProduitsController::addProducts' => [[], ['_controller' => 'App\\Controller\\ProduitsController::addProducts'], [], [['text', '/addProduit']], [], [], []],
    'App\Controller\ProduitsController::reassort' => [[], ['_controller' => 'App\\Controller\\ProduitsController::reassort'], [], [['text', '/reassort']], [], [], []],
];
